### ISSUE TITLE
is it possible to change the out put directories?

### ISSUE THREAD

**Issue by ComptonAlvaro** [axodox/AxoTools#85]
I would like to know if it is posssible to change the output directories of the XML and reports, because in the debug folder for me it is not the best place to have it, because they are big files.

Thanks.

**Comment by axodox** [comment]
Not as of now, but I can add something :)

**Comment by ComptonAlvaro** [comment]
Nice to hear. About that, if i am not wrong the settings are general for all the projects and solutions, so if it would be possible to set the folder for each test project it would be nice.

I mean if I have test for my project 1 and tests for my project 2, I would like to be able to set the folder f:\tests\project1 for the project 1 and f:\tests\project2 for the project 2 and son on.

Thanks so much for this extension.

**Comment by axodox** [comment]
I am letting you know, that the upcoming AxoCover version, which can downloaded [here](https://github.com/axodox/AxoTools/releases/tag/master-1.1.222), stores these files under your solution folder. They are under /.axoCover/runs and /.axoCover/reports.

Now let me summarize what points I have extracted from your messages:
**Files are big**: 
- This can be addressed by redirecting the folders above with mklink /j cmd command to another place.
- Also AxoCover can clean up the files using the setting output directories section.

**Files are deployed in the same folder**:
- Is this causing a problem?
- Would a "deploy different test projects in separate directories" solve it? Or you want to have a granular approach and chose it for each project?

**Manual override for deployment paths**:
- This would likely to become a user option, since we cannot ensure the absolute paths to exist on different machines (assuming other settings are committed to source control).
- Relative paths could work of course.

Solutions I see - _please note that I try to only work on stuff which is important, as I am doing this in my free time, so even if I am completely OK with the features you suggest and would gladly merge them if someone implements them, I will try to minimize the work on my side_:
- **Enable auto-cleanup**: this would simply delete the output files automatically from time to time (at basically could be just delete on next run, but could be also made more sophisticated like deleting after certain time, or if certain amount of space is used up)
- **Add option to deploy projects in different directories** (but the place would not be user selectable, it would just add subfolders under current folder)
- **Redirect the root folder for runs and reports (but not per project)** - as user option
- **Specify output directory per project** - well I am not convinced this is really needed yet :)

**Comment by axodox** [comment]
Since this thread was inactive for long I will close it to clean the issue board. The only current target from this is to have auto-cleanup. If you still need help on this please reopen and provide more information. Thank you.
