### ISSUE TITLE
Is it possible to see in output window the complete commands that it is used?

### ISSUE THREAD

**Issue by ComptonAlvaro** [axodox/AxoTools#86]
I am trying to run a test with opencover in command line, but despite to set the filters to run only the tests of one class in my test assembly, it is run all the tests in all classes, so I guess i am doing something wrong.

However, I can see that when I select this class in AxoTools in the output window I can see that only the methods in the class that I have selected are run.

I am using MSTest in both cases.

Could you add the option in the output window to see the complete commands that are run?

Could you tell me here the command that you are using?

Thanks so much.

**Comment by axodox** [comment]
AxoCover 1.1 and forward uses its own runner, which is controlled over network, not command line. For 1.0 I only provide bugfixes. I will think if generating console commands would otherwise be feasible. It would be easier for me to provide a simple command line runner which uses the runner of AxoCover.

**Comment by ComptonAlvaro** [comment]
Thanks for clear this and thanks for this tool.

**Comment by axodox** [comment]
Closed since AxoCover 1.1 is using its own runner. You may check [mstest](https://msdn.microsoft.com/en-us/library/ms182489.aspx) and [opencover](https://github.com/OpenCover/opencover/wiki/Usage) command line to set up your CI server.
