### ISSUE TITLE
Branches coverage fail

### ISSUE THREAD

**Issue by maosierra** [axodox/AxoTools#90]
Hello Axo team, thank you for the tools is very useful!

I have a problem with the Coverage Report for one  method: 
![image](https://user-images.githubusercontent.com/5141362/26984799-6a7c6c66-4d06-11e7-8dc3-68c5cfed9f77.png)

I have all test case but the coverage shows me only 86%:
![image](https://user-images.githubusercontent.com/5141362/26984846-98ee6a22-4d06-11e7-97bc-fe4980c6b6a8.png)

How to know what happens in this case? 

Thank you again.

**Comment by axodox** [comment]
Based on the image I see the following possibilities:
- You might have forgot to rebuild the project before running the test the last time (considering the branch symbols in lines where is only the parenthesis)
- Your test invokes all lines of your code, but there are some branches not covered, e.g. you have an if {...}, and you always execute its body, but do not test the case when the condition is false.
- If these are not the case, it is possible that the compiler emitted some branches which are not immediately obvious.

I suggest to do rebuild & rerun, and check if you really cover all branches, including the case mentioned above. If it is still the same, I suggest to create an example project, which you can attach as a zip here, unless you want to check the MSIL emitted by the compiler yourself. 

Side note: AxoCover is generating the coverage report with OpenCover, so you might need to go to their issue board, in the case we cannot resolve the issue here.

**Comment by axodox** [comment]
This thread was inactive for a long while. I reviewed the case again, and it is clear on the screenshot that the code coverage does not match with the code (see: branch dots where there are no branches). If you still experience the issue please reopen. Thanks.

**Comment by ZombieProtectionAgency** [comment]
So it is a little late but I just ran into this issue. As far as I can tell it looks like every `await` statement inside of a foreach block causes a single yellow dot to appear.

![image](https://user-images.githubusercontent.com/9204874/39586216-96736656-4ec4-11e8-8492-5dca6d45b4ca.png)

![image](https://user-images.githubusercontent.com/9204874/39586257-aaf6877a-4ec4-11e8-95a2-77ccb31a5f98.png)

![image](https://user-images.githubusercontent.com/9204874/39586684-abb8a868-4ec5-11e8-9ece-b6bf6a09582b.png)
