### ISSUE TITLE
Group anonymous methods under their owner

### ISSUE THREAD

**Issue by kurthamilton** [axodox/AxoTools#92]
Methods declared like 
`public async Task AsyncMethod() `
are ignored by code coverage.

In the example images, AsyncMethodOne() isn't discovered.
![2017-06-14 12_05_43-unittestproject1 - microsoft visual studio administrator](https://user-images.githubusercontent.com/4037252/27129397-090bb57a-50fa-11e7-9f3c-48e99da77f19.png)
![2017-06-14 12_05_54-unittestproject1 - microsoft visual studio administrator](https://user-images.githubusercontent.com/4037252/27129406-108cfb7e-50fa-11e7-98d0-ac336690ed3c.png)

I am using the latest pre-release version 1.1.193.

**Comment by axodox** [comment]
Need to check this, it can be either:
- A problem with parsing OpenCover output - you can check this by opening the output directory from AxoCover settings, and check the xml report files there. If those do not have your async method, then...
- It is a problem with OpenCover, in this case report it there: https://github.com/OpenCover/opencover/issues

**Comment by kurthamilton** [comment]
Thanks for replying promptly. It is in the coverage report:

![2017-06-14 15_13_44-c__users_kurt-hamilton_documents_visual studio 2017_projects_unittestproject1_ a](https://user-images.githubusercontent.com/4037252/27136806-1c796700-5114-11e7-9d0f-f9c08180bfc4.png)

**Comment by axodox** [comment]
OK, I see the output is missing some things, like we do not have any branch or sequence points, and the FileRef for the source is missing too - it is likely that these cause it to be omitted by AxoCover. I will check.

**Comment by axodox** [comment]
I checked the report, and actually it is correct right now. Well sort of...

As you might know when you use async-await the flow of code execution is changed drastically, so much in fact your async method is split up to multiple methods, like this:
![image](https://user-images.githubusercontent.com/22882208/27984485-6c7a31be-63d7-11e7-9e5f-eb9e1d493a2a.png)
That is why the method name is not on the coverage report, as there is nothing to cover there, and there is not associated source file either, since it is all auto-generated. The coverage displayed in the editor is also proper, since the compiled code is processed correctly, just the report display is a little harder to understand - but a stack trace would show the same names.

I changed the issue to be about presenting the anonymous methods under their original name.

**Comment by axodox** [comment]
I checked and it would require considerable time to improve the report, there are a number of issues:
- I cannot rely on the naming used, as that could change in a future version of .Net, and if I create an overload of the async function it quickly gets messy and complicated to do properly based on the name only.
- I cannot know where the original function is in the source since this is not in the OpenCover report - and might not be in the pdb either since there is no user code for this method.
- Another approach would be to read the assembly and scan the MSIL code, but that is subject to change as well.
So unless you have a better idea I will leave this as it is...

**Comment by axodox** [comment]
I am sorry, but will have to close this with won't fix for now :(
Thanks for info though!

**Comment by kurthamilton** [comment]
No worries. Thanks for taking the time to investigate.
